# Workflow used for publishing 

name: Publish a build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Gradle Build and Publish to Container Registry
    steps:
      - uses: actions/checkout@v3
      - name: Set up Zulu JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build with Gradle
        run: |          
          ./gradlew build

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_DEPLOY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push grpcbin
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/orkes-io/test-utils/grpcbin:latest